name: Run Every Minute

on:
  schedule:
    - cron: "* * * * *"   # Every minute
  workflow_dispatch:        # Optional: allows manual trigger

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "hello"
