name: CI Pipeline

on:
  schedule:
    - cron: "* * * * *"

jobs:
  Print:
    runs-on: ubuntu-latest

    steps:
      # Step 3: Install dependencies
      - name: Install dependencies
        run: echo "hello"
